### ISSUE TITLE
Screen Share not work in iOS

### ISSUE THREAD

**Issue by Karim-Sheetos2269** [AgoraIO-Extensions/Agora-Unity-Quickstart#239]
Hi,
This is video show the problem 
Also for your information, I tried it on an iPhone and screen sharing did not work either
https://drive.google.com/file/d/1hhaRseT8Nh9xOa7ObrnXZbSpDL3Hx5u4/view
Thanks

**Comment by xiayangqun** [comment]
1. Can you just run this example in a real iPhone/iPad but not in your Mac computer?
2. It look like you not follow the next action Indicate in the document

https://github.com/AgoraIO-Extensions/Agora-Unity-Quickstart/blob/main/API-Example-Unity/Assets/API-Example/Examples/Advanced/ScreenShare/ScreenShareGuide.md

## Manual Actions
Taking [the ShareScreen demo](https://github.com/AgoraIO-Extensions/Agora-Unity-Quickstart/tree/main/API-Example-Unity/Assets/API-Example/Examples/Advanced/ScreenShare) as example, the steps to properly share the screen on iOS should follow the steps:
1. The order of buttons press should be: Join Channel -> Start Sharing -> Start Publish
![ss_step1](https://user-images.githubusercontent.com/1261195/231244602-0609459e-aa40-4d0a-a816-7607a15b449f.jpg)
2. You should see StartScreenCapture call return 0.  Here you may see a white box, since ScreenRecording has not started.
![ss_step2](https://user-images.githubusercontent.com/1261195/231244623-092d3d71-e198-477c-901a-fd362f2e08cc.jpg)
3. Access the iOS quick control panel, long press the Screen Recording button
![ss_step3](https://user-images.githubusercontent.com/1261195/231244635-ef61fa63-a1b9-4dd7-9c51-fc9e991c8528.jpg)
4. Select the App, in this example, we named it as "AgoraIOSScreenSharing".  And press "Start Broadcast"
![ss_step4](https://user-images.githubusercontent.com/1261195/231246651-b1c02bc2-bd46-4191-b053-79507aedcb10.jpg)
5. The "Screen Recording" title should be shown:
![ss_step5](https://user-images.githubusercontent.com/1261195/231244674-351d667a-7b69-44a1-8901-020df4b6136d.jpg)
6. Switch back into the App, you should see the local view now is showing the screen.
![IMG_0061](https://user-images.githubusercontent.com/1261195/231244714-3ae3b7e8-e964-4075-926a-ed23fff17ade.PNG)

**Comment by Karim-Sheetos2269** [comment]
Thanks bro ,  Screen Share work finally

**Comment by Karim-Sheetos2269** [comment]
Thank you my brother
Sorry for the delay, responding due to emergency circumstances
Screen sharing worked finallu
But when I uploaded it to the  app store, this error appeared. What is the solution, please?
https://drive.google.com/file/d/1uNAcGzwOkj-790XHPEb7VJ0J-WdO1Y27/view?usp=sharing
Thanks

**Comment by xiayangqun** [comment]
> Thank you my brother Sorry for the delay, responding due to emergency circumstances Screen sharing worked finally But when I uploaded it to the app store, this error appeared. What is the solution, please? https://drive.google.com/file/d/1uNAcGzwOkj-790XHPEb7VJ0J-WdO1Y27/view?usp=sharing https://drive.google.com/file/d/1KjQyvD1Mg9vDN0jzSVv20pCZq8ruygl6/view?usp=sharing Thanks

you should only "Embed $ Sign" in your main targets like this
![企业微信截图_ab067ff6-a1e8-406e-95e2-de564a4e9437](https://github.com/AgoraIO-Extensions/Agora-Unity-Quickstart/assets/11383154/e21525d7-5254-45a1-b4e2-9ae1be5a0f6a)

But "Do Not Embed" in other targets
![企业微信截图_d3fa3b55-4893-4735-9d31-c665812c911f](https://github.com/AgoraIO-Extensions/Agora-Unity-Quickstart/assets/11383154/539a55e7-4620-4e32-9f1f-97772932161c)

**Comment by Karim-Sheetos2269** [comment]
Thanks alot bro i will try it
